local jobs = {
    [0] = { full = 'None', short = 'NA' },
    [1] = { full = 'Warrior', short = 'WAR' },
    [2] = { full = 'Monk', short = 'MNK' },
    [3] = { full = 'White Mage', short = 'WHM' },
    [4] = { full = 'Black Mage', short = 'BLM' },
    [5] = { full = 'Red Mage', short = 'RDM' },
    [6] = { full = 'Thief', short = 'THF' },
    [7] = { full = 'Paladin', short = 'PLD' },
    [8] = { full = 'Dark Knight', short = 'DRK' },
    [9] = { full = 'Beastmaster', short = 'BST' },
    [10] = { full = 'Bard', short = 'BRD' },
    [11] = { full = 'Ranger', short = 'RNG' },
    [12] = { full = 'Samurai', short = 'SAM' },
    [13] = { full = 'Ninja', short = 'NIN' },
    [14] = { full = 'Dragoon', short = 'DRG' },
    [15] = { full = 'Summoner', short = 'SMN' },
    [16] = { full = 'Blue Mage', short = 'BLU' },
    [17] = { full = 'Corsair', short = 'COR' },
    [18] = { full = 'Puppetmaster', short = 'PUP' },
    [19] = { full = 'Dancer', short = 'DNC' },
    [20] = { full = 'Scholar', short = 'SCH' },
    [21] = { full = 'Geomancer', short = 'GEO' },
    [22] = { full = 'Rune Fencer', short = 'RUN' }
}
return jobs
